# Generated by Django 3.2 on 2021-05-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts_name', models.CharField(max_length=500)),
                ('facts_value', models.CharField(max_length=500)),
                ('facts_description', models.CharField(max_length=500)),
            ],
        ),
    ]
