# Generated by Django 3.2 on 2021-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_facts_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=500)),
                ('skill_percentage', models.CharField(max_length=500)),
            ],
        ),
    ]
