# Generated by Django 3.2 on 2021-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_skills_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('course_year', models.CharField(max_length=500)),
                ('course_university', models.CharField(max_length=500)),
                ('course_info', models.CharField(max_length=500)),
                ('course_grade', models.CharField(max_length=500)),
            ],
        ),
    ]
