# Generated by Django 3.2 on 2021-05-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=5000)),
            ],
        ),
    ]
