# Generated by Django 3.2 on 2021-05-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_resume_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=5000)),
                ('client_name', models.CharField(max_length=5000)),
                ('duration', models.CharField(max_length=1000)),
                ('organization', models.CharField(max_length=1000)),
                ('technologies_used', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.project_details')),
            ],
        ),
    ]
