# Generated by Django 3.2 on 2021-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_project_desc_project_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.CharField(max_length=1000)),
                ('contact_value', models.CharField(max_length=5000)),
            ],
        ),
    ]
